ALTER TABLE users ADD COLUMN password VARCHAR(255);
ALTER TABLE users ADD COLUMN role VARCHAR(50);

UPDATE users
SET role = 'USER'
WHERE role IS NULL;

UPDATE users
SET password = 'TEMP_PASSWORD'
WHERE password IS NULL;

ALTER TABLE users ALTER COLUMN password SET NOT NULL;
ALTER TABLE users ALTER COLUMN role SET NOT NULL;